### ISSUE TITLE
read measurement fails 

### ISSUE THREAD

**Issue by opc241** [Sensirion/embedded-scd#49]
Hi Team, 

I had problems with reading measurement values with the latest release of the SCD30 with Embedded-SCD 2.1.2: 

I got crazy values, which caused the crc check to fail, cause those values represent a CO2 of about -1900ppm. 
After a lot of testing i found out, that inserting a delay in function `scd30_read_measurement `(scd30.c LOC: 79) between the following `sensirion_i2c_write_cmd(SCD30_I2C_ADDRESS, SCD30_CMD_READ_MEASUREMENT);` and `error = sensirion_i2c_read_words_as_bytes(SCD30_I2C_ADDRESS, &data[0][0], SENSIRION_NUM_WORDS(data));` like: 

```
int16_t scd30_read_measurement(float* co2_ppm, float* temperature,
                               float* humidity) 
{
    int16_t error;
    uint8_t data[3][4];

    error =
        sensirion_i2c_write_cmd(SCD30_I2C_ADDRESS, SCD30_CMD_READ_MEASUREMENT);
	
	if (error != NO_ERROR)
        return error;
	
	sensirion_sleep_usec(SCD30_WRITE_DELAY_US); // @Markus

    error = sensirion_i2c_read_words_as_bytes(SCD30_I2C_ADDRESS, &data[0][0],
                                              SENSIRION_NUM_WORDS(data));
    if (error != NO_ERROR)
        return error;

	

    *co2_ppm = sensirion_bytes_to_float(data[0]);
    *temperature = sensirion_bytes_to_float(data[1]);
    *humidity = sensirion_bytes_to_float(data[2]);

    return NO_ERROR;
}
```

... solved this problem and correct readings came out of the sensor. 
Could anyone possibly confirm this solution?

Thanks for your those great products like the SCD30! 

Greetings from Bavaria,
Markus

**Comment by MBjoern** [comment]
Hi Markus

Thank you for the update on this matter. We'll look into it. In the mean time, if the readings are correct, when adding the delay on your platform, then we're glad that you've found a workaround.
