### ISSUE TITLE
Allowable ambient pressure range

### ISSUE THREAD

**Issue by guarndt** [Sensirion/embedded-scd#9]
According to the [interface description](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9.5_CO2/Sensirion_CO2_Sensors_SCD30_Interface_Description.pdf) Section 1.3.1, the allowable pressure range is between 700 and 1200 mbar. Function scd_start_periodic_measurement in scd30.c assumes 700 to 1400 mbar. Which is correct?

**Comment by abrauchli** [comment]
Hi @guarndt, many thanks for your input. We clarified this inconsistency internally: 700-1400mbar is the correct range, we'll update the interface description accordingly. I'll leave the issue open until this is done.

Thanks

**Comment by abrauchli** [comment]
Thanks for your patience. I'm closing this since the document was updated (section 1.4.1) http://www.sensirion.com/file/scd30_interface_description and now reflects the 1400mbar as max value.
